### PR TITLE
Module 3 - Week 4 - Space Travelers Hub: Complete Application

### PR DESCRIPTION
**Pull request by 187jjay187**
### In this Milestone we implemented the following tasks:

- Setup application with react, react-router, redux, jest and linters
- Create app header
- Fetch rocket data from API and display in rocket component
- Fetch mission data from API and display in mission component
- Implement booking and cancellation actions for rockets
- Implement booking and cancellation actions for missions
- Implement badge switches for rockets and missions
- Display reserved rockets in profile component
- Display reserved missions in profile component

### CODE REVIEW

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @187jjay187 & @usamamaliq,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] You should write unit tests with React Testing Library and Jest (for unit tests).

> NOTE: Kindly make sure to add tests for all your components and functions.

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by 187jjay187** [comment]
Good day @mahbubul14 

I'd like to thank you for the code review and optional suggestions, however, we've followed all of the [KanbanBoard](https://github.com/187jjay187/react-gp/projects/1) task requirements and completed the application with all of our tasks in the kanban board being marked as completed but unit tests were not one of the requirements in the kanban board

**Comment by mahbubul14** [comment]
> Good day @mahbubul14
> 
> I'd like to thank you for the code review and optional suggestions, however, we've followed all of the [KanbanBoard](https://github.com/187jjay187/react-gp/projects/1) task requirements and completed the application with all of our tasks in the kanban board being marked as completed but unit tests were not one of the requirements in the kanban board

Hello @187jjay187, Here is the project requirement. Could you please check? :+1: 
test

**Review by AshakaE — CHANGES_REQUESTED** [review]
Hi @187jjay187  🙋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] Testing is a requirement for this project to be approved, I believe it's an oversight in the kanban board. Kindly write the unit tests for your project,  The kanban board will be updated ASAP.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by 187jjay187** [comment]
We've implemented the testing requirements for the project

**Review by ichala — APPROVED** [review]
Hi @187jjay187   ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
